"""Autogenerate migration

Revision ID: 568ae930581b
Revises: 
Create Date: 2025-01-26 22:09:54.092133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568ae930581b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProductOwner', 'Name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ProductOwner', 'Email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ProductOwner', 'RoleName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ProjectDetails', 'ProductOwnerId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ProjectDetails', 'ProjectName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ProjectDetails', 'StartDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ProjectDetails', 'EndDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ProjectDetails', 'Status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('ProjectUsers', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ProjectUsers', 'ProjectId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Reports', 'ReportId',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Reports', 'Filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Reports', 'Filepath',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('Reports', 'GeneratedOn',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('Reports', 'Frequency',
               existing_type=sa.TEXT(),
               type_=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='frequencyenum'),
               existing_nullable=False)
    op.alter_column('ScrumMasters', 'Email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('ScrumMasters', 'Name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Tasks', 'UserStoryID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Tasks', 'TaskName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Tasks', 'AssignedUserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Tasks', 'TaskStatus',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('UserRoles', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserRoles', 'RoleName',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('UserStories', 'SprintId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('UserStories', 'PlannedSprint',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserStories', 'ActualSprint',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserStories', 'Description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('UserStories', 'StoryPoint',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserStories', 'MOSCOW',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('UserStories', 'Assignee',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('UserStories', 'Status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(None, 'UserStories', type_='foreignkey')
    op.drop_column('UserStories', 'Dependency')
    op.alter_column('Users', 'UserName',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Users', 'Password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Users', 'Email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Users', 'Role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('Users', 'Name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('Users', 'Approved',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('Users', 'DOB',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('Users', 'login_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('Users', 'logout_time',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('Users', 'profile_picture',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'profile_picture',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Users', 'logout_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Users', 'login_time',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Users', 'DOB',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Users', 'Approved',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Users', 'Name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Users', 'Role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('Users', 'Email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Users', 'Password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Users', 'UserName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('UserStories', sa.Column('Dependency', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'UserStories', 'Users', ['Assignee'], ['UserID'])
    op.alter_column('UserStories', 'Status',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('UserStories', 'Assignee',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserStories', 'MOSCOW',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('UserStories', 'StoryPoint',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('UserStories', 'Description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('UserStories', 'ActualSprint',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('UserStories', 'PlannedSprint',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('UserStories', 'SprintId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('UserRoles', 'RoleName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('UserRoles', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Tasks', 'TaskStatus',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('Tasks', 'AssignedUserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Tasks', 'TaskName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Tasks', 'UserStoryID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ScrumMasters', 'Name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ScrumMasters', 'Email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('Reports', 'Frequency',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='frequencyenum'),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Reports', 'GeneratedOn',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('Reports', 'Filepath',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Reports', 'Filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Reports', 'ReportId',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('ProjectUsers', 'ProjectId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ProjectUsers', 'UserID',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ProjectDetails', 'Status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ProjectDetails', 'EndDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ProjectDetails', 'StartDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ProjectDetails', 'ProjectName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ProjectDetails', 'ProductOwnerId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ProductOwner', 'RoleName',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ProductOwner', 'Email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ProductOwner', 'Name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
